/* ------------------------------------------------------------
   1. 헬스장 회원 관리 (TBL_GRADE_21, TBL_MEMBER_21)
   ------------------------------------------------------------ */
-- 테이블 삭제
DROP TABLE TBL_MEMBER_21 CASCADE CONSTRAINTS;
DROP TABLE TBL_GRADE_21 CASCADE CONSTRAINTS;

-- 테이블 생성
CREATE TABLE TBL_GRADE_21 (
    GCODE VARCHAR2(5) PRIMARY KEY,
    GNAME VARCHAR2(20)
);

CREATE TABLE TBL_MEMBER_21 (
    MNO   NUMBER(6) PRIMARY KEY,
    NAME  VARCHAR2(20),
    PHONE VARCHAR2(13),
    GCODE VARCHAR2(5),
    CONSTRAINT FK_MEMBER_GRADE FOREIGN KEY (GCODE) REFERENCES TBL_GRADE_21(GCODE)
);

-- 데이터 삽입
INSERT INTO TBL_GRADE_21 VALUES ('A', 'VIP');
INSERT INTO TBL_GRADE_21 VALUES ('B', '일반');

INSERT INTO TBL_MEMBER_21 VALUES (1, '김철수', '010-1111-2222', 'A');
INSERT INTO TBL_MEMBER_21 VALUES (2, '이영희', '010-2222-3333', 'B');
INSERT INTO TBL_MEMBER_21 VALUES (3, '박민수', '010-3333-4444', 'A');


/* ------------------------------------------------------------
   2. 온라인 쇼핑몰 주문 (TBL_CUSTOMER_22, TBL_PRODUCT_22, TBL_ORDER_22)
   ------------------------------------------------------------ */
-- 테이블 삭제
DROP TABLE TBL_ORDER_22 CASCADE CONSTRAINTS;
DROP TABLE TBL_PRODUCT_22 CASCADE CONSTRAINTS;
DROP TABLE TBL_CUSTOMER_22 CASCADE CONSTRAINTS;

-- 테이블 생성
CREATE TABLE TBL_CUSTOMER_22 (
    CNO   NUMBER(6) PRIMARY KEY,
    CNAME VARCHAR2(20)
);

CREATE TABLE TBL_PRODUCT_22 (
    PNO   NUMBER(6) PRIMARY KEY,
    PNAME VARCHAR2(50),
    PRICE NUMBER(7)
);

CREATE TABLE TBL_ORDER_22 (
    ONO   NUMBER(6) PRIMARY KEY,
    CNO   NUMBER(6),
    PNO   NUMBER(6),
    QTY   NUMBER(4),
    ODATE DATE,
    CONSTRAINT FK_ORDER_CUST FOREIGN KEY (CNO) REFERENCES TBL_CUSTOMER_22(CNO),
    CONSTRAINT FK_ORDER_PROD FOREIGN KEY (PNO) REFERENCES TBL_PRODUCT_22(PNO)
);

-- 데이터 삽입
INSERT INTO TBL_CUSTOMER_22 VALUES (101, '김철수');
INSERT INTO TBL_CUSTOMER_22 VALUES (102, '이영희');

INSERT INTO TBL_PRODUCT_22 VALUES (1001, '무선마우스', 15000);
INSERT INTO TBL_PRODUCT_22 VALUES (1002, '기계식키보드', 50000);

INSERT INTO TBL_ORDER_22 VALUES (1001, 101, 1001, 2, DATE '2025-01-01');
INSERT INTO TBL_ORDER_22 VALUES (1002, 102, 1002, 1, DATE '2025-01-02');



/* ------------------------------------------------------------
   3. 학사관리 시스템 (TBL_STUDENT_23, TBL_SUBJECT_23, TBL_ENROLL_23)
   ------------------------------------------------------------ */
-- 테이블 삭제
DROP TABLE TBL_ENROLL_23 CASCADE CONSTRAINTS;
DROP TABLE TBL_SUBJECT_23 CASCADE CONSTRAINTS;
DROP TABLE TBL_STUDENT_23 CASCADE CONSTRAINTS;

-- 테이블 생성
CREATE TABLE TBL_STUDENT_23 (
    SNO   NUMBER(6) PRIMARY KEY,
    SNAME VARCHAR2(20),
    MAJOR VARCHAR2(30)
);

CREATE TABLE TBL_SUBJECT_23 (
    SUBNO   NUMBER(4) PRIMARY KEY,
    SUBNAME VARCHAR2(50),
    CREDIT  NUMBER(1)
);

CREATE TABLE TBL_ENROLL_23 (
    ENO   NUMBER(6) PRIMARY KEY,
    SNO   NUMBER(6),
    SUBNO NUMBER(4),
    GRADE VARCHAR2(2),
    CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY (SNO) REFERENCES TBL_STUDENT_23(SNO),
    CONSTRAINT FK_ENROLL_SUBJECT FOREIGN KEY (SUBNO) REFERENCES TBL_SUBJECT_23(SUBNO)
);

-- 데이터 삽입
INSERT INTO TBL_STUDENT_23 VALUES (202301, '김지훈', '컴퓨터공학');
INSERT INTO TBL_STUDENT_23 VALUES (202302, '이서연', '컴퓨터공학');
INSERT INTO TBL_STUDENT_23 VALUES (202303, '박민호', '경영학');

INSERT INTO TBL_SUBJECT_23 VALUES (501, '데이터베이스', 3);
INSERT INTO TBL_SUBJECT_23 VALUES (502, '운영체제', 3);

INSERT INTO TBL_ENROLL_23 VALUES (1, 202301, 501, 'A');
INSERT INTO TBL_ENROLL_23 VALUES (2, 202301, 502, 'B');
INSERT INTO TBL_ENROLL_23 VALUES (3, 202302, 501, 'A');
INSERT INTO TBL_ENROLL_23 VALUES (4, 202303, 501, 'C');


/* ------------------------------------------------------------
   4. 도서관 대출 시스템 (TBL_MEMBER_24, TBL_BOOK_24, TBL_RENT_24)
   ------------------------------------------------------------ */
-- 테이블 삭제
DROP TABLE TBL_RENT_24 CASCADE CONSTRAINTS;
DROP TABLE TBL_BOOK_24 CASCADE CONSTRAINTS;
DROP TABLE TBL_MEMBER_24 CASCADE CONSTRAINTS;

-- 테이블 생성
CREATE TABLE TBL_MEMBER_24 (
    MNO   NUMBER(6) PRIMARY KEY,
    MNAME VARCHAR2(20),
    PHONE VARCHAR2(13)
);

CREATE TABLE TBL_BOOK_24 (
    BNO    NUMBER(6) PRIMARY KEY,
    BTITLE VARCHAR2(50),
    AUTHOR VARCHAR2(30)
);

CREATE TABLE TBL_RENT_24 (
    RNO       NUMBER(6) PRIMARY KEY,
    MNO       NUMBER(6),
    BNO       NUMBER(6),
    RENTDATE  DATE,
    DUEDATE   DATE,
    RETURN_YN CHAR(1),
    CONSTRAINT FK_RENT_MEMBER FOREIGN KEY (MNO) REFERENCES TBL_MEMBER_24(MNO),
    CONSTRAINT FK_RENT_BOOK FOREIGN KEY (BNO) REFERENCES TBL_BOOK_24(BNO)
);

-- 데이터 삽입
INSERT INTO TBL_MEMBER_24 VALUES (1, '김철수', '010-1111-2222');
INSERT INTO TBL_MEMBER_24 VALUES (2, '이영희', '010-2222-3333');

INSERT INTO TBL_BOOK_24 VALUES (101, '자바의 정석', '남궁성');
INSERT INTO TBL_BOOK_24 VALUES (102, '파이썬 완벽 가이드', 'Mark');

INSERT INTO TBL_RENT_24 VALUES (1001, 1, 101, DATE '2025-03-01', DATE '2025-03-08', 'N');
INSERT INTO TBL_RENT_24 VALUES (1002, 2, 102, DATE '2025-03-02', DATE '2025-03-09', 'N');
INSERT INTO TBL_RENT_24 VALUES (1003, 1, 101, DATE '2025-02-01', DATE '2025-02-08', 'Y');


/* ------------------------------------------------------------
   5. 호텔 예약 시스템 (TBL_GUEST_25, TBL_ROOM_25, TBL_RESERVE_25)
   ------------------------------------------------------------ */
-- 테이블 삭제
DROP TABLE TBL_RESERVE_25 CASCADE CONSTRAINTS;
DROP TABLE TBL_ROOM_25 CASCADE CONSTRAINTS;
DROP TABLE TBL_GUEST_25 CASCADE CONSTRAINTS;

-- 테이블 생성
CREATE TABLE TBL_GUEST_25 (
    GNO   NUMBER(6) PRIMARY KEY,
    GNAME VARCHAR2(20),
    PHONE VARCHAR2(13)
);

CREATE TABLE TBL_ROOM_25 (
    RNO   NUMBER(4) PRIMARY KEY,
    RTYPE VARCHAR2(20),
    PRICE NUMBER(7)
);

CREATE TABLE TBL_RESERVE_25 (
    RSNO    NUMBER(6) PRIMARY KEY,
    GNO     NUMBER(6),
    RNO     NUMBER(4),
    CHECKIN DATE,
    NIGHTS  NUMBER(3),
    CONSTRAINT FK_RESERVE_GUEST FOREIGN KEY (GNO) REFERENCES TBL_GUEST_25(GNO),
    CONSTRAINT FK_RESERVE_ROOM FOREIGN KEY (RNO) REFERENCES TBL_ROOM_25(RNO)
);

-- 데이터 삽입
INSERT INTO TBL_GUEST_25 VALUES (1, '김철수', '010-1111-2222');
INSERT INTO TBL_GUEST_25 VALUES (2, '이영희', '010-2222-3333');

INSERT INTO TBL_ROOM_25 VALUES (101, '더블', 100000);
INSERT INTO TBL_ROOM_25 VALUES (302, '스위트', 200000);

INSERT INTO TBL_RESERVE_25 VALUES (5001, 1, 101, DATE '2025-05-02', 2);
INSERT INTO TBL_RESERVE_25 VALUES (5002, 2, 302, DATE '2025-05-10', 3);
INSERT INTO TBL_RESERVE_25 VALUES (5003, 1, 101, DATE '2025-04-28', 1);


/* ------------------------------------------------------------
   6. 프로젝트 관리 시스템 (TBL_DEPT_26, TBL_EMP_26, TBL_PROJECT_26, TBL_ASSIGN_26)
   ------------------------------------------------------------ */
-- 테이블 삭제
DROP TABLE TBL_ASSIGN_26 CASCADE CONSTRAINTS;
DROP TABLE TBL_PROJECT_26 CASCADE CONSTRAINTS;
DROP TABLE TBL_EMP_26 CASCADE CONSTRAINTS;
DROP TABLE TBL_DEPT_26 CASCADE CONSTRAINTS;

-- 테이블 생성
CREATE TABLE TBL_DEPT_26 (
    DNO   NUMBER(4) PRIMARY KEY,
    DNAME VARCHAR2(30)
);

CREATE TABLE TBL_EMP_26 (
    ENO      NUMBER(6) PRIMARY KEY,
    ENAME    VARCHAR2(20),
    DNO      NUMBER(4),
    POSITION VARCHAR2(20),
    CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DNO) REFERENCES TBL_DEPT_26(DNO)
);

CREATE TABLE TBL_PROJECT_26 (
    PNO    NUMBER(6) PRIMARY KEY,
    PNAME  VARCHAR2(50),
    STATUS VARCHAR2(10)
);

CREATE TABLE TBL_ASSIGN_26 (
    ASNO NUMBER(6) PRIMARY KEY,
    ENO  NUMBER(6),
    PNO  NUMBER(6),
    ROLE VARCHAR2(20),
    CONSTRAINT FK_ASSIGN_EMP FOREIGN KEY (ENO) REFERENCES TBL_EMP_26(ENO),
    CONSTRAINT FK_ASSIGN_PROJ FOREIGN KEY (PNO) REFERENCES TBL_PROJECT_26(PNO)
);

-- 데이터 삽입
INSERT INTO TBL_DEPT_26 VALUES (10, '개발팀');
INSERT INTO TBL_DEPT_26 VALUES (20, '기획팀');
INSERT INTO TBL_DEPT_26 VALUES (30, 'QA팀');

INSERT INTO TBL_EMP_26 VALUES (2001, '김개발', 10, '대리');
INSERT INTO TBL_EMP_26 VALUES (2005, '이기획', 20, '과장');
INSERT INTO TBL_EMP_26 VALUES (2003, '박테스트', 30, '사원');

INSERT INTO TBL_PROJECT_26 VALUES (1001, '쇼핑몰 고도화', '진행중');
INSERT INTO TBL_PROJECT_26 VALUES (1002, '그룹웨어 개선', '진행중');
INSERT INTO TBL_PROJECT_26 VALUES (1003, '보안 시스템 개선', '보류');

INSERT INTO TBL_ASSIGN_26 VALUES (1, 2001, 1001, '개발');
INSERT INTO TBL_ASSIGN_26 VALUES (2, 2005, 1001, '기획');
INSERT INTO TBL_ASSIGN_26 VALUES (3, 2003, 1002, '테스트');
INSERT INTO TBL_ASSIGN_26 VALUES (4, 2001, 1003, '개발');

/* ------------------------------------------------------------
   7. 월별 매출 내역 (TBL_CATEGORY_27, TBL_PRODUCT_27, TBL_SALE_27)
   ------------------------------------------------------------ */
-- 테이블 삭제
DROP TABLE TBL_SALE_27 CASCADE CONSTRAINTS;
DROP TABLE TBL_PRODUCT_27 CASCADE CONSTRAINTS;
DROP TABLE TBL_CATEGORY_27 CASCADE CONSTRAINTS;

-- 테이블 생성
CREATE TABLE TBL_CATEGORY_27 (
    CNO   NUMBER(4) PRIMARY KEY,
    CNAME VARCHAR2(30)
);

CREATE TABLE TBL_PRODUCT_27 (
    PNO   NUMBER(6) PRIMARY KEY,
    PNAME VARCHAR2(50),
    CNO   NUMBER(4),
    PRICE NUMBER(7),
    CONSTRAINT FK_PROD_CAT FOREIGN KEY (CNO) REFERENCES TBL_CATEGORY_27(CNO)
);

CREATE TABLE TBL_SALE_27 (
    SNO   NUMBER(6) PRIMARY KEY,
    PNO   NUMBER(6),
    QTY   NUMBER(4),
    SDATE DATE,
    CONSTRAINT FK_SALE_PROD FOREIGN KEY (PNO) REFERENCES TBL_PRODUCT_27(PNO)
);

-- 데이터 삽입
INSERT INTO TBL_CATEGORY_27 VALUES (10, '주변기기');
INSERT INTO TBL_CATEGORY_27 VALUES (20, '노트북');

INSERT INTO TBL_PRODUCT_27 VALUES (1001, '무선마우스', 10, 15000);
INSERT INTO TBL_PRODUCT_27 VALUES (1002, '게이밍키보드', 10, 50000);
INSERT INTO TBL_PRODUCT_27 VALUES (1003, '사무용노트북', 20, 900000);

INSERT INTO TBL_SALE_27 VALUES (3001, 1001, 2, DATE '2025-06-01');
INSERT INTO TBL_SALE_27 VALUES (3002, 1002, 1, DATE '2025-06-01');
INSERT INTO TBL_SALE_27 VALUES (3003, 1003, 1, DATE '2025-05-20');


/* ------------------------------------------------------------
   8. 택배 배송 추적 (TBL_CUSTOMER_28, TBL_PRODUCT_28, TBL_DELIVERY_28)
   ------------------------------------------------------------ */
-- 테이블 삭제
DROP TABLE TBL_DELIVERY_28 CASCADE CONSTRAINTS;
DROP TABLE TBL_PRODUCT_28 CASCADE CONSTRAINTS;
DROP TABLE TBL_CUSTOMER_28 CASCADE CONSTRAINTS;

-- 테이블 생성
CREATE TABLE TBL_CUSTOMER_28 (
    CNO   NUMBER(6) PRIMARY KEY,
    CNAME VARCHAR2(20),
    PHONE VARCHAR2(13)
);

CREATE TABLE TBL_PRODUCT_28 (
    PNO   NUMBER(6) PRIMARY KEY,
    PNAME VARCHAR2(50)
);

CREATE TABLE TBL_DELIVERY_28 (
    DNO      NUMBER(6) PRIMARY KEY,
    CNO      NUMBER(6),
    PNO      NUMBER(6),
    FROM_LOC VARCHAR2(30),
    TO_LOC   VARCHAR2(30),
    STATUS   VARCHAR2(10),
    CONSTRAINT FK_DELIV_CUST FOREIGN KEY (CNO) REFERENCES TBL_CUSTOMER_28(CNO),
    CONSTRAINT FK_DELIV_PROD FOREIGN KEY (PNO) REFERENCES TBL_PRODUCT_28(PNO)
);

-- 데이터 삽입
INSERT INTO TBL_CUSTOMER_28 VALUES (1, '김철수', '010-1111-2222');
INSERT INTO TBL_CUSTOMER_28 VALUES (2, '이영희', '010-2222-3333');

INSERT INTO TBL_PRODUCT_28 VALUES (1001, '무선마우스');
INSERT INTO TBL_PRODUCT_28 VALUES (1002, '노트북');

INSERT INTO TBL_DELIVERY_28 VALUES (8001, 1, 1001, '서울', '부산', '배송중');
INSERT INTO TBL_DELIVERY_28 VALUES (8002, 2, 1002, '인천', '대구', '배송중');
INSERT INTO TBL_DELIVERY_28 VALUES (8003, 1, 1002, '서울', '대전', '배송완료');


/* ------------------------------------------------------------
   9. 급여 계산 시스템 (TBL_DEPT_29, TBL_EMP_29, TBL_WTIME_29, TBL_PAYCONF_29)
   ------------------------------------------------------------ */
-- 테이블 삭제
DROP TABLE TBL_PAYCONF_29 CASCADE CONSTRAINTS;
DROP TABLE TBL_WTIME_29 CASCADE CONSTRAINTS;
DROP TABLE TBL_EMP_29 CASCADE CONSTRAINTS;
DROP TABLE TBL_DEPT_29 CASCADE CONSTRAINTS;

-- 테이블 생성
CREATE TABLE TBL_DEPT_29 (
    DNO   NUMBER(4) PRIMARY KEY,
    DNAME VARCHAR2(30)
);

CREATE TABLE TBL_EMP_29 (
    ENO     NUMBER(6) PRIMARY KEY,
    ENAME   VARCHAR2(20),
    DNO     NUMBER(4),
    BASEPAY NUMBER(10),
    CONSTRAINT FK_EMP29_DEPT FOREIGN KEY (DNO) REFERENCES TBL_DEPT_29(DNO)
);

CREATE TABLE TBL_WTIME_29 (
    WNO       NUMBER(6) PRIMARY KEY,
    ENO       NUMBER(6),
    WORK_DATE DATE,
    HOURS     NUMBER(4),
    CONSTRAINT FK_WTIME_EMP FOREIGN KEY (ENO) REFERENCES TBL_EMP_29(ENO)
);

CREATE TABLE TBL_PAYCONF_29 (
    DNO        NUMBER(4),
    HOURLY_PAY NUMBER(7),
    CONSTRAINT FK_PAYCONF_DEPT FOREIGN KEY (DNO) REFERENCES TBL_DEPT_29(DNO)
);

-- 데이터 삽입
INSERT INTO TBL_DEPT_29 VALUES (10, '개발팀');
INSERT INTO TBL_DEPT_29 VALUES (20, '기획팀');

INSERT INTO TBL_EMP_29 VALUES (2001, '김대리', 10, 2000000);
INSERT INTO TBL_EMP_29 VALUES (2002, '이주임', 20, 1800000);

INSERT INTO TBL_WTIME_29 VALUES (1, 2001, DATE '2025-06-01', 8);
INSERT INTO TBL_WTIME_29 VALUES (2, 2001, DATE '2025-06-02', 12);
INSERT INTO TBL_WTIME_29 VALUES (3, 2002, DATE '2025-06-01', 10);

INSERT INTO TBL_PAYCONF_29 VALUES (10, 15000);
INSERT INTO TBL_PAYCONF_29 VALUES (20, 12000);


/* ------------------------------------------------------------
   10. 쇼핑몰 리뷰 관리 (TBL_CUSTOMER_30 등 5개 테이블)
   ------------------------------------------------------------ */
-- 테이블 삭제
DROP TABLE TBL_REVIEW_30 CASCADE CONSTRAINTS;
DROP TABLE TBL_ORDER_30 CASCADE CONSTRAINTS;
DROP TABLE TBL_PRODUCT_30 CASCADE CONSTRAINTS;
DROP TABLE TBL_CATEGORY_30 CASCADE CONSTRAINTS;
DROP TABLE TBL_CUSTOMER_30 CASCADE CONSTRAINTS;

-- 테이블 생성
CREATE TABLE TBL_CUSTOMER_30 (
    CNO   NUMBER(6) PRIMARY KEY,
    CNAME VARCHAR2(20)
);

CREATE TABLE TBL_CATEGORY_30 (
    CNO2  NUMBER(4) PRIMARY KEY,
    CNAME VARCHAR2(30)
);

CREATE TABLE TBL_PRODUCT_30 (
    PNO   NUMBER(6) PRIMARY KEY,
    PNAME VARCHAR2(50),
    CNO2  NUMBER(4),
    CONSTRAINT FK_PROD30_CAT FOREIGN KEY (CNO2) REFERENCES TBL_CATEGORY_30(CNO2)
);

CREATE TABLE TBL_ORDER_30 (
    ONO   NUMBER(6) PRIMARY KEY,
    CNO   NUMBER(6),
    PNO   NUMBER(6),
    ODATE DATE,
    CONSTRAINT FK_ORDER30_CUST FOREIGN KEY (CNO) REFERENCES TBL_CUSTOMER_30(CNO),
    CONSTRAINT FK_ORDER30_PROD FOREIGN KEY (PNO) REFERENCES TBL_PRODUCT_30(PNO)
);

CREATE TABLE TBL_REVIEW_30 (
    RNO     NUMBER(6) PRIMARY KEY,
    ONO     NUMBER(6),
    SCORE   NUMBER(1),
    CONTENT VARCHAR2(200),
    CONSTRAINT FK_REVIEW_ORDER FOREIGN KEY (ONO) REFERENCES TBL_ORDER_30(ONO)
);

-- 데이터 삽입
INSERT INTO TBL_CUSTOMER_30 VALUES (1, '김철수');
INSERT INTO TBL_CUSTOMER_30 VALUES (2, '이영희');

INSERT INTO TBL_CATEGORY_30 VALUES (10, '주변기기');

INSERT INTO TBL_PRODUCT_30 VALUES (1001, '무선마우스', 10);
INSERT INTO TBL_PRODUCT_30 VALUES (1002, '게이밍키보드', 10);

INSERT INTO TBL_ORDER_30 VALUES (5001, 1, 1001, DATE '2025-03-02');
INSERT INTO TBL_ORDER_30 VALUES (5002, 2, 1002, DATE '2025-03-05');

INSERT INTO TBL_REVIEW_30 VALUES (9001, 5001, 5, '너무 좋습니다');
INSERT INTO TBL_REVIEW_30 VALUES (9002, 5002, 4, '만족합니다');

COMMIT;